model: gemini-2.5-flash-preview-04-17
api: google
max_tokens: null
temperature: null
top_p: null
concurrent_requests: 8
config:
  max_output_tokens: 64000
read_cost: 0.15
write_cost: 3.5
human_readable_id: gemini-2.5-flash (think)
date: "2025-04-18"
