model: claude-opus-4-20250514
api: anthropic
max_tokens: 64000
concurrent_requests: 1
temperature: 1
top_p: null
thinking:
  type: enabled 
  budget_tokens: 32000
read_cost: 15
write_cost: 75
batch_processing: false
human_readable_id: Claude-4-Opus (Think)
date: "2025-05-14"